(define (domain sokoban)
        (:requirements :strips)
        (:constants player box wall)
        (:predicates (at ?p ?x)
                        (adjacent ?x ?y)
                        (adjacent_2 ?x ?y)
                        (use_teleport)
        )
        (:action move-player
                :parameters (?x ?y)
                :precondition (and (adjacent ?x ?y)
                                        (not (at box ?y))
                                        (not (at wall ?y))
                                        (at player ?x))
                :effect		   (and (at player ?y)
                                        (not (at player ?x))))
        (:action push-box
                :parameters (?x ?y ?z)
                :precondition (and (at player ?x)
                                (at box ?y)
                                (not (at box ?z))
                                (not (at wall ?z))
                                (adjacent ?x ?y)
                                (adjacent ?y ?z)
                                (adjacent_2 ?x ?z))
                :effect (and (at box ?z)
                                (not(at box ?y))
                                (at player ?y)
                                (not(at player ?x))))
        (:action teleport
                :parameters (?x ?y)
                :precondition (and (at player ?x)
                                (not (at box ?y))
                                (not (at wall ?y))
                                (use_teleport)
                )
                :effect         (and (at player ?y)
                                (not (at player ?x))
                                (not(use_teleport)))
                )
)